# This workflow will do a clean installation of node dependencies, cache/restore them, build the source code and run tests across different versions of node
# For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-nodejs

name: Node.js CI

on : 
  push:
    branches:
      - main
      - R01
      - R02
      - R03
      - R04
      - R05
  pull_request:
      branches:
        - main
        - R01
        - R02
        - R03
        - R04
        - R05

jobs:
  build:
    runs-on: ubuntu-latest

    services:
      mysql:
        image: mysql:latest
        env:
          MYSQL_ROOT_PASSWORD: root
          MYSQL_DATABASE: forum
        ports:
          - 3306:3306
        options: --health-cmd="mysqladmin ping" --health-interval=10s --health-timeout=5s --health-retries=3


    env:
      NODE_ENV: travis
      JWT_SECRET: JWT_SECRET

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Setup Node.js
        uses: actions/setup-node@v2
        with:
          node-version: 14

      - name : Start mysql
        run : sudo service mysql start 
      - name: Set up MySQL database
        run: |
          docker exec -i $(docker ps -q --filter "name=mysql") mysql -uroot -proot -e "CREATE DATABASE IF NOT EXISTS forum default character set utf8mb4 collate utf8mb4_unicode_ci;"
      - name : Install sequelize-cli
        run: npm install sequelize-cli -g
      - name: Install dependencies
        run: npm install

      - name: Run database migrations
        run: npx sequelize db:migrate

      - name: Run database seeders
        run: npx sequelize db:seed:all

      - name : Run test
        run: npm test
